import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import { z } from "zod";
import fs from "fs/promises";
import path from "path";
import os from "os";
import { exec } from "child_process";
import { promisify } from "util";
import { runCodingAgent, parseSummary } from "./agent.js";

const execAsync = promisify(exec);
const app = express();
app.use(express.json());

function parseRepoUrl(url) {
  const match = url.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  if (!match) throw new Error(`Cannot parse GitHub repo URL: ${url}`);
  return { owner: match[1], repo: match[2].replace(/\.git$/, "") };
}

function slugify(text) {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40);
  return slug || Math.random().toString(36).slice(2, 8);
}

function extractTitle(summary) {
  for (const line of summary.split("\n").map((l) => l.trim()).filter(Boolean)) {
    const clean = line.replace(/^[#*\->]+\s*/, "").replace(/\*\*/g, "").replace(/`/g, "");
    if (clean.length > 5) return clean.slice(0, 72);
  }
  return summary.slice(0, 72);
}

async function hasChanges(workDir) {
  const { stdout } = await execAsync("git status --porcelain", { cwd: workDir });
  return stdout.trim().length > 0;
}

function createServer() {
  const server = new McpServer({ name: "api-endpoints", version: "1.0.0" });

  server.tool(
    "implement_and_pr",
    "프롬프트를 받아 GitHub 저장소 코드를 자동으로 수정하고 PR을 생성합니다",
    {
      prompt: z.string().describe("구현할 기능 또는 수정 사항 설명"),
    },
    async ({ prompt }, extra) => {
      const sendLog = async (msg) => {
        process.stderr.write(`[api-endpoints] ${msg}\n`);
        try {
          await extra.sendNotification({
            method: "notifications/message",
            params: { level: "info", logger: "api-endpoints", data: msg },
          });
        } catch {}
      };

      const repo_url = process.env.GITHUB_REPO_URL;
      const base_branch = process.env.BASE_BRANCH || "main";
      const token = process.env.GITHUB_TOKEN;
      if (!token) return { content: [{ type: "text", text: "Error: GITHUB_TOKEN이 설정되지 않았습니다." }] };
      if (!repo_url) return { content: [{ type: "text", text: "Error: GITHUB_REPO_URL이 설정되지 않았습니다." }] };

      const { owner, repo } = parseRepoUrl(repo_url);
      const authedUrl = `https://${token}@github.com/${owner}/${repo}.git`;

      const now = new Date();
      const datePart = now.toISOString().slice(0, 16).replace(/[-T:]/g, "").slice(0, 12);
      const branchName = `agent/api/${datePart}-${slugify(prompt)}`;

      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "api-endpoints-agent-"));

      try {
        await sendLog(`📦 저장소 클론 중... (${owner}/${repo}@${base_branch})`);
        await execAsync(`git clone --depth=1 --branch ${base_branch} ${authedUrl} .`, { cwd: tmpDir });
        await execAsync('git config user.email "agent@rorr.club"', { cwd: tmpDir });
        await execAsync('git config user.name "api-endpoints-agent"', { cwd: tmpDir });

        await sendLog(`🌿 브랜치 생성: ${branchName}`);
        await execAsync(`git checkout -b ${branchName}`, { cwd: tmpDir });

        await sendLog(`🤖 Claude 에이전트 실행 중... (프롬프트: "${prompt.slice(0, 60)}")`);
        const raw = await runCodingAgent(prompt, tmpDir, sendLog);
        const { title: agentTitle, summary } = parseSummary(raw);
        await sendLog("✅ Claude 에이전트 완료");

        if (!(await hasChanges(tmpDir))) {
          return { content: [{ type: "text", text: `에이전트가 실행됐지만 변경된 파일이 없습니다.\n\n${summary}` }] };
        }

        await sendLog("💾 변경사항 커밋 & 푸시 중...");
        await execAsync("git add -A", { cwd: tmpDir });
        await execAsync(
          `git commit -m "feat: ${prompt.slice(0, 60).replace(/"/g, "'")}\n\nGenerated by api-endpoints-agent"`,
          { cwd: tmpDir }
        );
        await execAsync(`git push origin ${branchName}`, { cwd: tmpDir });

        await sendLog("🔗 PR 생성 중...");
        const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            title: agentTitle || extractTitle(summary),
            body: `## Summary\n\n${summary}\n\n---\n*🤖 Generated by api-endpoints-agent*`,
            head: branchName,
            base: base_branch,
          }),
        });

        const pr = await prRes.json();
        if (!prRes.ok) throw new Error(`GitHub API error: ${JSON.stringify(pr)}`);

        await sendLog(`🎉 PR 생성 완료! ${pr.html_url}`);
        return {
          content: [{
            type: "text",
            text: `✅ PR 생성 완료!\n\nURL: ${pr.html_url}\n브랜치: ${branchName}\n\n## 변경 내용\n${summary}`,
          }],
        };
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true });
      }
    }
  );

  server.tool(
    "design_endpoints",
    "DB 스키마 기반으로 RESTful 엔드포인트 목록을 설계합니다",
    {
      schema: z.string().describe("db-schema 에이전트 결과"),
      feature: z.string().describe("구현할 기능 설명"),
    },
    async ({ schema, feature }) => ({
      content: [{ type: "text", text: `[api-endpoints] "${feature}" 엔드포인트 설계\n스키마: ${schema}\n실제 서비스 연결 시 Method/Path/설명 테이블을 반환합니다.` }],
    })
  );

  server.tool(
    "generate_request_response",
    "특정 엔드포인트의 요청/응답 JSON 예시를 생성합니다",
    {
      method: z.string().describe("HTTP 메서드"),
      path: z.string().describe("엔드포인트 경로"),
    },
    async ({ method, path }) => ({
      content: [{ type: "text", text: `[api-endpoints] ${method} ${path}\n실제 서비스 연결 시 요청/응답 JSON 예시를 반환합니다.` }],
    })
  );

  server.tool(
    "check_auth",
    "엔드포인트별 인증/인가 필요 여부를 분석합니다",
    { endpoints: z.string().describe("엔드포인트 목록") },
    async ({ endpoints }) => ({
      content: [{ type: "text", text: `[api-endpoints] 인증 분석:\n${endpoints}\n실제 서비스 연결 시 인증 레벨과 권한 목록을 반환합니다.` }],
    })
  );

  return server;
}

app.post("/mcp", async (req, res) => {
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  const server = createServer();
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
  await server.close();
});

app.get("/health", (_, res) => res.json({ status: "ok", server: "api-endpoints" }));

app.listen(5003, () => process.stdout.write("api-endpoints MCP server running on :5003\n"));
